/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.p2proyecto_estructuradatos;

import java.awt.Color;

/**
 *
 * @author jenni
 */
public class RegistroNotasJfr extends javax.swing.JFrame {

    /**
     * Creates new form RegistroNotasJfr
     */
    public RegistroNotasJfr() {
        initComponents();
        nombreEsTxt.setOpaque(false); 
        nombreEsTxt.setBackground(new Color(0, 0, 0, 0));
        notaP1Txt.setOpaque(false); 
        notaP1Txt.setBackground(new Color(0, 0, 0, 0));
        notaP2Txt.setOpaque(false); 
        notaP2Txt.setBackground(new Color(0, 0, 0, 0));
        notaP3Txt.setOpaque(false); 
        notaP3Txt.setBackground(new Color(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreEsTxt = new javax.swing.JTextField();
        notaP1Txt = new javax.swing.JTextField();
        notaP2Txt = new javax.swing.JTextField();
        notaP3Txt = new javax.swing.JTextField();
        RegistrarAlumnoBtt = new javax.swing.JButton();
        borrarCamposBtt = new javax.swing.JButton();
        ordenarListaBtt = new javax.swing.JButton();
        ordenarCalificacionesBtt = new javax.swing.JButton();
        buscarAlumno = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaEstudiantesTb = new javax.swing.JTable();
        interfazGUI = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreEsTxt.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        nombreEsTxt.setForeground(new java.awt.Color(255, 255, 255));
        nombreEsTxt.setBorder(null);
        nombreEsTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreEsTxtActionPerformed(evt);
            }
        });
        getContentPane().add(nombreEsTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 300, 30));

        notaP1Txt.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        notaP1Txt.setForeground(new java.awt.Color(255, 255, 255));
        notaP1Txt.setBorder(null);
        getContentPane().add(notaP1Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 90, 30));

        notaP2Txt.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        notaP2Txt.setForeground(new java.awt.Color(255, 255, 255));
        notaP2Txt.setBorder(null);
        notaP2Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notaP2TxtActionPerformed(evt);
            }
        });
        getContentPane().add(notaP2Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 500, 90, 30));

        notaP3Txt.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        notaP3Txt.setForeground(new java.awt.Color(255, 255, 255));
        notaP3Txt.setBorder(null);
        getContentPane().add(notaP3Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 500, 100, 30));

        RegistrarAlumnoBtt.setText("registrar");
        getContentPane().add(RegistrarAlumnoBtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, 300, 40));

        borrarCamposBtt.setText("jButton1");
        borrarCamposBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarCamposBttActionPerformed(evt);
            }
        });
        getContentPane().add(borrarCamposBtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 633, 40, 40));

        ordenarListaBtt.setText("jButton1");
        getContentPane().add(ordenarListaBtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 390, 50, 40));

        ordenarCalificacionesBtt.setText("jButton1");
        getContentPane().add(ordenarCalificacionesBtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 480, 50, 40));

        buscarAlumno.setText("jButton1");
        getContentPane().add(buscarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(1035, 300, 50, 40));

        listaEstudiantesTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombres", "Nota P1", "Nota P2", "Nota P3", "Nota Final"
            }
        ));
        jScrollPane1.setViewportView(listaEstudiantesTb);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 520, 560));

        interfazGUI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registroInterfaz.png"))); // NOI18N
        getContentPane().add(interfazGUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreEsTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreEsTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreEsTxtActionPerformed

    private void notaP2TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notaP2TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notaP2TxtActionPerformed

    private void borrarCamposBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarCamposBttActionPerformed
        nombreEsTxt.setText("");
        notaP1Txt.setText("");
        notaP2Txt.setText("");
        notaP3Txt.setText("");
    }//GEN-LAST:event_borrarCamposBttActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroNotasJfr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroNotasJfr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroNotasJfr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroNotasJfr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroNotasJfr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RegistrarAlumnoBtt;
    private javax.swing.JButton borrarCamposBtt;
    private javax.swing.JButton buscarAlumno;
    private javax.swing.JLabel interfazGUI;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listaEstudiantesTb;
    private javax.swing.JTextField nombreEsTxt;
    private javax.swing.JTextField notaP1Txt;
    private javax.swing.JTextField notaP2Txt;
    private javax.swing.JTextField notaP3Txt;
    private javax.swing.JButton ordenarCalificacionesBtt;
    private javax.swing.JButton ordenarListaBtt;
    // End of variables declaration//GEN-END:variables
}
